[package]
name = "hugin"
version = "0.1.0"
authors = ["Etienne MARAIS <etiennemarais@maiste.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
actix-web = "3"
lazy_static = "1.4.0"
